In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
sb.set()

In [2]:
terrorism = pd.read_csv('terrorism.csv', encoding='ISO-8859-1')
terrorism.shape

C:\Users\pinoc\AppData\Local\Temp\ipykernel_5996\2075809476.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  terrorism = pd.read_csv('terrorism.csv', encoding='ISO-8859-1')

(181691, 135)

In [3]:
# to display every row and column
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
terrorism.head()
df = terrorism.copy()

## Remove duplicates

In [5]:
df = df.drop_duplicates()
df.shape # no duplicates

(181691, 135)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Columns: 135 entries, eventid to related
dtypes: float64(55), int64(22), object(58)
memory usage: 187.1+ MB

## Remove text data (not needed)
--> Text descriptions (objects)

In [7]:
text_df = df.select_dtypes(include=['object'])
text_df.head()

,approxdate,resolution,country_txt,region_txt,provstate,city,location,summary,alternative_txt,attacktype1_txt,attacktype2_txt,attacktype3_txt,targtype1_txt,targsubtype1_txt,corp1,target1,natlty1_txt,targtype2_txt,targsubtype2_txt,corp2,target2,natlty2_txt,targtype3_txt,targsubtype3_txt,corp3,target3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,claimmode_txt,claimmode2_txt,claimmode3_txt,weaptype1_txt,weapsubtype1_txt,weaptype2_txt,weapsubtype2_txt,weaptype3_txt,weapsubtype3_txt,weaptype4_txt,weapsubtype4_txt,weapdetail,propextent_txt,propcomment,divert,kidhijcountry,ransomnote,hostkidoutcome_txt,addnotes,scite1,scite2,scite3,dbsource,related
0,NaN,NaN,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,NaN,NaN,NaN,Assassination,NaN,NaN,Private Citizens & Property,Named Civilian,NaN,Julio Guzman,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANO-D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,NaN
1,NaN,NaN,Mexico,North America,Federal,Mexico city,NaN,NaN,NaN,Hostage Taking (Kidnapping),NaN,NaN,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,"Nadine Chaval, daughter",Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23rd of September Communist League,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mexico,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,NaN
2,NaN,NaN,Philippines,Southeast Asia,Tarlac,Unknown,NaN,NaN,NaN,Assassination,NaN,NaN,Journalists & Media,Radio Journalist/Staff/Facility,Voice of America,Employee,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,NaN
3,NaN,NaN,Greece,Western Europe,Attica,Athens,NaN,NaN,NaN,Bombing/Explosion,NaN,NaN,Government (Diplomatic),Embassy/Consulate,NaN,U.S. Embassy,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosives,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,Explosive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,NaN
4,NaN,NaN,Japan,East Asia,Fukouka,Fukouka,NaN,NaN,NaN,Facility/Infrastructure Attack,NaN,NaN,Government (Diplomatic),Embassy/Consulate,NaN,U.S. Consulate,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,NaN

In [8]:
df = df.select_dtypes(exclude=['object'])
df.describe()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,1.816910e+05,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,177135.000000,1.771340e+05,181685.000000,181691.000000,181691.000000,181691.000000,181691.000000,181690.000000,29011.000000,181690.000000,181691.000000,181691.000000,181691.000000,6314.000000,428.000000,181691.000000,171318.000000,180132.000000,11144.000000,10685.000000,10828.000000,1176.000000,1097.000000,1147.000000,181311.000000,1955.000000,320.000000,181691.000000,110576.000000,112202.000000,115571.000000,19083.000000,1890.000000,616.000000,318.000000,133.000000,4839.000000,181691.000000,160923.000000,13127.000000,11542.000000,1863.000000,1693.000000,73.000000,70.000000,171378.000000,117245.000000,114733.000000,165380.000000,116989.000000,112548.000000,181691.000000,64065.000000,3.898900e+04,181513.000000,13572.000000,13517.000000,4063.000000,8124.000000,77381.000000,1.350000e+03,5.630000e+02,7.740000e+02,552.000000,10991.000000,10400.000000,181691.000000,181691.000000,181691.000000,181691.000000
mean,2.002705e+11,2002.638997,6.467277,15.505644,0.045346,131.968501,7.160938,23.498343,-4.586957e+02,1.451452,0.068297,0.988530,0.993093,0.875668,-0.523171,1.292923,0.137773,0.889598,0.036507,3.247547,3.719512,5.245327,8.439719,46.971474,127.686441,10.247218,55.311652,131.179442,10.021259,55.548769,144.564952,0.081440,0.265473,0.193750,0.002950,-65.361154,-1.517727,0.049666,7.022848,0.247619,7.176948,0.411950,6.729323,-6.296342,6.447325,11.117162,6.812524,10.754029,6.911433,11.643237,6.246575,10.842857,2.403272,0.045981,0.508058,3.167668,0.038944,0.107163,-0.544556,3.295403,2.088119e+05,0.059054,4.533230,-0.353999,-46.793933,-32.516371,-0.145811,3.172530e+06,5.784865e+05,7.179437e+05,240.378623,4.629242,-29.018269,-4.543731,-4.464398,0.090010,-3.945952
std,1.325957e+09,13.259430,3.388303,8.814045,0.208063,112.414535,2.933408,18.569242,2.047790e+05,0.995430,0.284553,0.106483,0.082823,0.329961,2.455819,0.703729,0.344663,0.313391,0.187549,1.915772,2.272023,2.246642,6.653838,30.953357,89.299120,5.709076,25.640310,125.951485,5.723447,26.288955,163.299295,0.273511,0.441698,0.395854,0.054234,216.536633,12.830346,1.093195,2.476851,0.974018,2.783725,0.492962,2.908003,4.234620,2.173435,6.495612,2.277081,7.594574,2.177956,8.493166,1.507212,8.192672,11.545741,5.681854,4.199937,35.949392,3.057361,1.488881,3.122889,0.486912,1.552463e+07,0.461244,202.316386,6.835645,82.800405,121.209205,1.207861,3.021157e+07,7.077924e+06,1.014392e+07,2940.967293,2.035360,65.720119,4.543547,4.637152,0.568457,4.691325
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,4.000000,1.000000,-53.154613,-8.618590e+07,1.000000,-9.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-9.000000,1.000000,-9.000000,1.000000,0.000000,1.000000,-9.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,-9.900000e+01,-9.000000,-99.000000,-99.000000,-99.000000,-99.000000,-9.000000,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-99.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.991021e+11,1991.000000,4.000000,8.000000,0.000000,78.000000,5.000000,11.510046,4.545640e+00,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,2.000000,2.000000,3.000000,22.000000,83.000000,4.000000,34.000000,92.000000,3.000000,33.000000,75.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,6.000000,0.000000,6.000000,0.000000,4.000000,-9.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,1.000000,0.000000,-99.000000,-99.000000,0.000000,0.000000e+00,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.009022e+11,2009.000000,6.000000,15.000000,0.000000,98.000000,6.000000,31.467463,4.324651e+01,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,7.000000,4.000000,35.000000,101.000000,14.000000,67.000000,98.000000,14.000000,67.000000,110.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,8.000000,0.000000,7.000000,0.000000,7.000000,-9.000000,6.000000,12.000000,6.000000,7.000000,6.000000,7.000000,6.000000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,-9.900000e+01,0.000000,2.000000,0.000000,-99.000000,-99.000000,0.000000,1.500000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,0.000000,-9.000000,-9.000000,0.000000,0.000000
75%,2.014081e+11,2014.000000,9.000000,23.000000,0.000000,160.000000,10.000000,34.685087,6.871033e+01,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,7.000000,14.000000,74.000000,173.000000,14.000000,69.000000,182.000000,14.000000,73.000000,182.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,8.000000,1.000000,10.000000,1.000000,9.000000,0.000000,6.000000,16.000000,8.000000,18.000000,9.000000,20.000000,6.000000,16.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,4.000000,1.000000e+03,0.000000,4.000000,0.000000,0.000000,4.000000,0.000000,4.000000e+05,0.000000e+00,1.273412e+03,0.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2.017123e+11,2017.000000,12.000000,31.000000,1.000000,1004.000000,12.000000,74.633553,1.793667e+02,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,9.000000,9.000000,8.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,1.000000,1.000000,1.000000,1.000000,25000.000000,406.000000,1.000000,10.000000,1.000000,10.000000,1.000000,10.000000,1.000000,13.000000,31.000000,13.000000,31.000000,13.000000,28.000000,12.000000,28.000000,1570.000000,1360.000000,500.000000,8191.000000,751.000000,200.000000,1.000000,4.000000,2.700000e+09,1.000000,17000.000000,86.000000,999.000000,2454.000000,1.000000,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2769.000000,1.000000,1.000000,1.000000,1.000000

## Convert negative (invalid) values to null
Only latitude and longitude can be negative

In [9]:
non_neg = df.drop(columns=['latitude', 'longitude']) # negative columns
neg = df[['latitude', 'longitude']] # non-negative columns

# new df
non_neg = non_neg.mask(non_neg < 0)
df = pd.concat([df[['latitude', 'longitude']], non_neg], axis=1)
df.describe()

,latitude,longitude,eventid,iyear,imonth,iday,extended,country,region,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,177135.000000,1.771340e+05,1.816910e+05,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181685.000000,181656.000000,181691.000000,181691.000000,181691.000000,167906.000000,29011.000000,181690.000000,181691.000000,181691.000000,181691.000000,6314.000000,428.000000,181691.000000,171318.000000,180132.000000,11144.000000,10685.000000,10828.000000,1176.000000,1097.000000,1147.000000,181311.000000,1955.000000,320.000000,181691.000000,28356.000000,110336.000000,114097.000000,19083.000000,1874.000000,616.000000,318.000000,133.000000,1405.000000,181691.000000,160923.000000,13127.000000,11542.000000,1863.000000,1693.000000,73.000000,70.000000,171378.000000,117245.000000,114733.000000,165380.000000,116989.000000,112548.000000,160305.000000,64065.000000,1.037600e+04,181196.000000,12335.000000,13456.000000,1937.000000,3869.000000,75983.000000,1.099000e+03,5.400000e+02,4.510000e+02,528.000000,10991.000000,6839.000000,89164.000000,89032.000000,181204.000000,97861.000000
mean,23.498343,-4.586957e+02,2.002705e+11,2002.638997,6.467277,15.505644,0.045346,131.968501,7.160938,1.451452,0.070044,0.988530,0.993093,0.875668,0.172722,1.292923,0.137773,0.889598,0.036507,3.247547,3.719512,5.245327,8.439719,46.971474,127.686441,10.247218,55.311652,131.179442,10.021259,55.548769,144.564952,0.081440,0.265473,0.193750,0.002950,32.170440,0.127628,0.166578,7.022848,0.326574,7.176948,0.411950,6.729323,0.311744,6.447325,11.117162,6.812524,10.754029,6.911433,11.643237,6.246575,10.842857,2.403272,0.045981,0.508058,3.167668,0.038944,0.107163,0.583469,3.295403,7.849073e+05,0.074902,14.915930,0.093193,9.994966,40.600155,0.017096,3.897125e+06,6.031300e+05,1.232196e+06,255.634470,4.629242,7.420529,0.080615,0.255975,0.114440,0.383462
std,18.569242,2.047790e+05,1.325957e+09,13.259430,3.388303,8.814045,0.208063,112.414535,2.933408,0.995430,0.255223,0.106483,0.082823,0.329961,0.378008,0.703729,0.344663,0.313391,0.187549,1.915772,2.272023,2.246642,6.653838,30.953357,89.299120,5.709076,25.640310,125.951485,5.723447,26.288955,163.299295,0.273511,0.441698,0.395854,0.054234,412.375875,2.079566,0.372600,2.476851,0.469085,2.783725,0.492962,2.908003,0.463371,2.173435,6.495612,2.277081,7.594574,2.177956,8.493166,1.507212,8.192672,11.545741,5.681854,4.199937,35.949392,3.057361,1.488881,0.492985,0.486912,3.008737e+07,0.263234,209.413964,1.618941,90.401485,143.678643,0.129630,3.344492e+07,7.226329e+06,1.327112e+07,3006.294428,2.035360,51.865115,0.272245,0.436410,0.318346,0.486232
min,-53.154613,-8.618590e+07,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.510046,4.545640e+00,1.991021e+11,1991.000000,4.000000,8.000000,0.000000,78.000000,5.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,2.000000,2.000000,3.000000,22.000000,83.000000,4.000000,34.000000,92.000000,3.000000,33.000000,75.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,6.000000,0.000000,6.000000,0.000000,4.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,5.000000e+03,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,31.467463,4.324651e+01,2.009022e+11,2009.000000,6.000000,15.000000,0.000000,98.000000,6.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,7.000000,4.000000,35.000000,101.000000,14.000000,67.000000,98.000000,14.000000,67.000000,110.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,8.000000,0.000000,7.000000,0.000000,7.000000,0.000000,6.000000,12.000000,6.000000,7.000000,6.000000,7.000000,6.000000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.480000e+04,0.000000,2.000000,0.000000,0.000000,4.000000,0.000000,6.000000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,34.685087,6.871033e+01,2.014081e+11,2014.000000,9.000000,23.000000,0.000000,160.000000,10.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,7.000000,14.000000,74.000000,173.000000,14.000000,69.000000,182.000000,14.000000,73.000000,182.000000,0.000000,1.000000,0.000000,0.000000,6.000000,0.000000,0.000000,8.000000,1.000000,10.000000,1.000000,9.000000,1.000000,6.000000,16.000000,8.000000,18.000000,9.000000,20.000000,6.000000,16.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,4.000000,5.000000e+04,0.000000,5.000000,0.000000,1.000000,18.000000,0.000000,6.247582e+05,0.000000e+00,7.787500e+04,0.000000,7.000000,3.000000,0.000000,1.000000,0.000000,1.000000
max,74.633553,1.793667e+02,2.017123e+11,2017.000000,12.000000,31.000000,1.000000,1004.000000,12.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,9.000000,9.000000,8.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,1.000000,1.000000,1.000000,1.000000,25000.000000,406.000000,1.000000,10.000000,1.000000,10.000000,1.000000,10.000000,1.000000,13.000000,31.000000,13.000000,31.000000,13.000000,28.000000,12.000000,28.000000,1570.000000,1360.000000,500.000000,8191.000000,751.000000,200.000000,1.000000,4.000000,2.700000e+09,1.000000,17000.000000,86.000000,999.000000,2454.000000,1.000000,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2769.000000,1.000000,1.000000,1.000000,1.000000

#### Define function to check null values

In [10]:
def check_null(df):
    na = df.isna().sum()
    na = pd.DataFrame(na, columns=['null'])

    # calculate percentage of null values
    na['percentage'] = na['null'] / df.shape[0] * 100
    na = na.sort_values(by='percentage', ascending=False)
    return na

na = check_null(df)
text_na = check_null(text_df)

## Drop columns
More than 70% NULL values

In [11]:
# normal df
col_drop = na[na['percentage'] > 70].index
df = df.drop(col_drop, axis=1)
# text df
col_drop = text_na[text_na['percentage'] > 70].index
text_df = text_df.drop(col_drop, axis=1)
df.head()

,latitude,longitude,eventid,iyear,imonth,iday,extended,country,region,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,targtype1,targsubtype1,natlty1,guncertain1,individual,nperpcap,claimed,weaptype1,weapsubtype1,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,ishostkid,ransom,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,18.456792,-69.951164,197000000001,1970,7,2,0,58,2,1.0,0.0,1,1,1,0.0,0.0,1,0,1,14,68.0,58.0,0.0,0,NaN,NaN,13,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,19.371887,-99.086624,197000000002,1970,0,0,0,130,1,1.0,0.0,1,1,1,0.0,0.0,1,0,6,7,45.0,21.0,0.0,0,NaN,NaN,13,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0
2,15.478598,120.599741,197001000001,1970,1,0,0,160,5,4.0,0.0,1,1,1,0.0,0.0,1,0,1,10,54.0,217.0,0.0,0,NaN,NaN,13,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,1.0,1.0
3,37.997490,23.762728,197001000002,1970,1,0,0,78,8,1.0,0.0,1,1,1,0.0,0.0,1,0,3,7,46.0,217.0,0.0,0,NaN,NaN,6,16.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,NaN,NaN,1.0,1.0
4,33.580412,130.396361,197001000003,1970,1,0,0,101,4,1.0,0.0,1,1,1,NaN,0.0,1,0,7,7,46.0,217.0,0.0,0,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,NaN,NaN,1.0,1.0

In [12]:
na = check_null(df)
na

                null  percentage
propextent    117626   64.739585
ransom        105708   58.180097
INT_IDEO       92659   50.998123
INT_LOG        92527   50.925472
INT_ANY        83830   46.138774
nperpcap       71355   39.272721
nwoundte       69143   38.055270
claimed        67594   37.202723
nkillter       66958   36.852678
nwoundus       64702   35.611010
nkillus        64446   35.470111
property       21386   11.770533
weapsubtype1   20768   11.430396
nwound         16311    8.977330
doubtterr      13785    7.587057
targsubtype1   10373    5.709144
nkill          10313    5.676120
longitude       4557    2.508104
latitude        4556    2.507554
natlty1         1559    0.858050
ishostkid        495    0.272441
INT_MISC         487    0.268037
guncertain1      380    0.209146
vicinity          35    0.019263
specificity        6    0.003302
multiple           1    0.000550
success            0    0.000000
extended           0    0.000000
suicide            0    0.000000
eventid            0    0.000000
iyear              0    0.000000
imonth             0    0.000000
individual         0    0.000000
iday               0    0.000000
country            0    0.000000
region             0    0.000000
attacktype1        0    0.000000
crit1              0    0.000000
crit2              0    0.000000
crit3              0    0.000000
weaptype1          0    0.000000
targtype1          0    0.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 42 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   latitude      177135 non-null  float64
 1   longitude     177134 non-null  float64
 2   eventid       181691 non-null  int64
 3   iyear         181691 non-null  int64
 4   imonth        181691 non-null  int64
 5   iday          181691 non-null  int64
 6   extended      181691 non-null  int64
 7   country       181691 non-null  int64
 8   region        181691 non-null  int64
 9   specificity   181685 non-null  float64
 10  vicinity      181656 non-null  float64
 11  crit1         181691 non-null  int64
 12  crit2         181691 non-null  int64
 13  crit3         181691 non-null  int64
 14  doubtterr     167906 non-null  float64
 15  multiple      181690 non-null  float64
 16  success       181691 non-null  int64
 17  suicide       181691 non-null  int64
 18  attacktype1   181691 non-null  int64
 19  targtype1     181691 non-null  int64
 20  targsubtype1  171318 non-null  float64
 21  natlty1       180132 non-null  float64
 22  guncertain1   181311 non-null  float64
 23  individual    181691 non-null  int64
 24  nperpcap      110336 non-null  float64
 25  claimed       114097 non-null  float64
 26  weaptype1     181691 non-null  int64
 27  weapsubtype1  160923 non-null  float64
 28  nkill         171378 non-null  float64
 29  nkillus       117245 non-null  float64
 30  nkillter      114733 non-null  float64
 31  nwound        165380 non-null  float64
 32  nwoundus      116989 non-null  float64
 33  nwoundte      112548 non-null  float64
 34  property      160305 non-null  float64
 35  propextent    64065 non-null   float64
 36  ishostkid     181196 non-null  float64
 37  ransom        75983 non-null   float64
 38  INT_LOG       89164 non-null   float64
 39  INT_IDEO      89032 non-null   float64
 40  INT_MISC      181204 non-null  float64
 41  INT_ANY       97861 non-null   float64
dtypes: float64(26), int64(16)
memory usage: 58.2 MB

#### Replace number with text data for eda

In [14]:
replace = ['country_txt', 'region_txt','location','attacktype1_txt','targtype1_txt',
           'targsubtype1_txt','natlty1_txt','weaptype1_txt','weapsubtype1_txt']
text_df = text_df[replace]

In [15]:
eda_df = df.copy()
eda_df['country'] = text_df['country_txt']
eda_df['region'] = text_df['region_txt']
eda_df['attacktype1'] = text_df['attacktype1_txt']
eda_df['targtype1'] = text_df['targtype1_txt']
eda_df['targsubtype1'] = text_df['targsubtype1_txt']
eda_df['natlty1'] = text_df['natlty1_txt']
eda_df['weaptype1'] = text_df['weaptype1_txt']
eda_df['weapsubtype1'] = text_df['weapsubtype1_txt']

eda_df.head()

,latitude,longitude,eventid,iyear,imonth,iday,extended,country,region,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,targtype1,targsubtype1,natlty1,guncertain1,individual,nperpcap,claimed,weaptype1,weapsubtype1,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,ishostkid,ransom,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,18.456792,-69.951164,197000000001,1970,7,2,0,Dominican Republic,Central America & Caribbean,1.0,0.0,1,1,1,0.0,0.0,1,0,Assassination,Private Citizens & Property,Named Civilian,Dominican Republic,0.0,0,NaN,NaN,Unknown,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,19.371887,-99.086624,197000000002,1970,0,0,0,Mexico,North America,1.0,0.0,1,1,1,0.0,0.0,1,0,Hostage Taking (Kidnapping),Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Belgium,0.0,0,NaN,NaN,Unknown,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0
2,15.478598,120.599741,197001000001,1970,1,0,0,Philippines,Southeast Asia,4.0,0.0,1,1,1,0.0,0.0,1,0,Assassination,Journalists & Media,Radio Journalist/Staff/Facility,United States,0.0,0,NaN,NaN,Unknown,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,1.0,1.0
3,37.997490,23.762728,197001000002,1970,1,0,0,Greece,Western Europe,1.0,0.0,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,United States,0.0,0,NaN,NaN,Explosives,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,NaN,NaN,1.0,1.0
4,33.580412,130.396361,197001000003,1970,1,0,0,Japan,East Asia,1.0,0.0,1,1,1,NaN,0.0,1,0,Facility/Infrastructure Attack,Government (Diplomatic),Embassy/Consulate,United States,0.0,0,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,NaN,NaN,1.0,1.0

## Convert to categorical

In [16]:
# function to convert numeric to categorical variables
def convert_categorical(df):
    for name in df:
        # calculate ratio of unique values to total values
        unique = df[name].nunique()
        total = df.shape[0]
        if unique/total < 0.05:
            # print(name)
            df[name] = df[name].astype('category')
    return df

df = convert_categorical(df)
eda_df = convert_categorical(eda_df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 42 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   latitude      177135 non-null  float64
 1   longitude     177134 non-null  float64
 2   eventid       181691 non-null  int64
 3   iyear         181691 non-null  category
 4   imonth        181691 non-null  category
 5   iday          181691 non-null  category
 6   extended      181691 non-null  category
 7   country       181691 non-null  category
 8   region        181691 non-null  category
 9   specificity   181685 non-null  category
 10  vicinity      181656 non-null  category
 11  crit1         181691 non-null  category
 12  crit2         181691 non-null  category
 13  crit3         181691 non-null  category
 14  doubtterr     167906 non-null  category
 15  multiple      181690 non-null  category
 16  success       181691 non-null  category
 17  suicide       181691 non-null  category
 18  attacktype1   181691 non-null  category
 19  targtype1     181691 non-null  category
 20  targsubtype1  171318 non-null  category
 21  natlty1       180132 non-null  category
 22  guncertain1   181311 non-null  category
 23  individual    181691 non-null  category
 24  nperpcap      110336 non-null  category
 25  claimed       114097 non-null  category
 26  weaptype1     181691 non-null  category
 27  weapsubtype1  160923 non-null  category
 28  nkill         171378 non-null  category
 29  nkillus       117245 non-null  category
 30  nkillter      114733 non-null  category
 31  nwound        165380 non-null  category
 32  nwoundus      116989 non-null  category
 33  nwoundte      112548 non-null  category
 34  property      160305 non-null  category
 35  propextent    64065 non-null   category
 36  ishostkid     181196 non-null  category
 37  ransom        75983 non-null   category
 38  INT_LOG       89164 non-null   category
 39  INT_IDEO      89032 non-null   category
 40  INT_MISC      181204 non-null  category
 41  INT_ANY       97861 non-null   category
dtypes: category(39), float64(2), int64(1)
memory usage: 11.7 MB

#### Set numeric variables to float

In [17]:
numeric = ['nperpcap', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte']
df[numeric] = df[numeric].astype(float)
eda_df[numeric] = eda_df[numeric].astype(float)

## Check for outliers in numeric columns

In [18]:
def count_outlier(df):
    rows = df.shape
    outlier = {}
    for col in df:
        if (df[col].dtype == 'category'):
            continue
        q1 = np.quantile(df[col], 0.25)
        q3 = np.quantile(df[col], 0.75)
        iqr = q3-q1
        upper = q3+1.5*iqr
        lower = q1-1.5*iqr
        count = sum((df[col] > upper) | (df[col] < lower))
        outlier[col] = count / rows[0] * 100
        outlier_df = pd.DataFrame.from_dict(outlier, orient='index', columns=['outliers'])
    return outlier_df

In [19]:
outlier = count_outlier(df)
outlier

           outliers
latitude        0.0
longitude       0.0
eventid         0.0
nperpcap        0.0
nkill           0.0
nkillus         0.0
nkillter        0.0
nwound          0.0
nwoundus        0.0
nwoundte        0.0

there are no outliers

## Impute NULL values

In [20]:
numeric_cols = df.select_dtypes(include='number').columns
categoric_cols = df.select_dtypes(include='category').columns

In [21]:
df.shape

(181691, 42)

In [22]:
def impute_null(df):
    na_col = df.isna().any() # check if column containes null value
    # impute missing value for numeric cols
    imputer = SimpleImputer(strategy='mean')
    for col in numeric_cols:
        if na_col[col]:
            col_data = df[[col]]
            imputed_col = imputer.fit_transform(col_data)
            # replace original column with imputed values
            imputed_col = pd.DataFrame(imputed_col)
            df[col] = imputed_col

    # impute missing value for categorical cols
    imputer_categorical = SimpleImputer(strategy='most_frequent')
    for col in categoric_cols:
        if na_col[col]:
            col_data = df[[col]]
            imputed_col = imputer_categorical.fit_transform(col_data)
            # replace original column with imputed values
            imputed_col = pd.DataFrame(imputed_col)
            df[col] = imputed_col

    return df

df = impute_null(df)
eda_df = impute_null(eda_df)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 42 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   latitude      181691 non-null  float64
 1   longitude     181691 non-null  float64
 2   eventid       181691 non-null  int64
 3   iyear         181691 non-null  category
 4   imonth        181691 non-null  category
 5   iday          181691 non-null  category
 6   extended      181691 non-null  category
 7   country       181691 non-null  category
 8   region        181691 non-null  category
 9   specificity   181691 non-null  float64
 10  vicinity      181691 non-null  float64
 11  crit1         181691 non-null  category
 12  crit2         181691 non-null  category
 13  crit3         181691 non-null  category
 14  doubtterr     181691 non-null  float64
 15  multiple      181691 non-null  float64
 16  success       181691 non-null  category
 17  suicide       181691 non-null  category
 18  attacktype1   181691 non-null  category
 19  targtype1     181691 non-null  category
 20  targsubtype1  181691 non-null  float64
 21  natlty1       181691 non-null  float64
 22  guncertain1   181691 non-null  float64
 23  individual    181691 non-null  category
 24  nperpcap      181691 non-null  float64
 25  claimed       181691 non-null  float64
 26  weaptype1     181691 non-null  category
 27  weapsubtype1  181691 non-null  float64
 28  nkill         181691 non-null  float64
 29  nkillus       181691 non-null  float64
 30  nkillter      181691 non-null  float64
 31  nwound        181691 non-null  float64
 32  nwoundus      181691 non-null  float64
 33  nwoundte      181691 non-null  float64
 34  property      181691 non-null  float64
 35  propextent    181691 non-null  float64
 36  ishostkid     181691 non-null  float64
 37  ransom        181691 non-null  float64
 38  INT_LOG       181691 non-null  float64
 39  INT_IDEO      181691 non-null  float64
 40  INT_MISC      181691 non-null  float64
 41  INT_ANY       181691 non-null  float64
dtypes: category(15), float64(26), int64(1)
memory usage: 40.2 MB

#### Convert variables back to categorical

In [24]:
df = convert_categorical(df)
eda_df = convert_categorical(eda_df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 42 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   latitude      181691 non-null  float64
 1   longitude     181691 non-null  float64
 2   eventid       181691 non-null  int64
 3   iyear         181691 non-null  category
 4   imonth        181691 non-null  category
 5   iday          181691 non-null  category
 6   extended      181691 non-null  category
 7   country       181691 non-null  category
 8   region        181691 non-null  category
 9   specificity   181691 non-null  category
 10  vicinity      181691 non-null  category
 11  crit1         181691 non-null  category
 12  crit2         181691 non-null  category
 13  crit3         181691 non-null  category
 14  doubtterr     181691 non-null  category
 15  multiple      181691 non-null  category
 16  success       181691 non-null  category
 17  suicide       181691 non-null  category
 18  attacktype1   181691 non-null  category
 19  targtype1     181691 non-null  category
 20  targsubtype1  181691 non-null  category
 21  natlty1       181691 non-null  category
 22  guncertain1   181691 non-null  category
 23  individual    181691 non-null  category
 24  nperpcap      181691 non-null  category
 25  claimed       181691 non-null  category
 26  weaptype1     181691 non-null  category
 27  weapsubtype1  181691 non-null  category
 28  nkill         181691 non-null  category
 29  nkillus       181691 non-null  category
 30  nkillter      181691 non-null  category
 31  nwound        181691 non-null  category
 32  nwoundus      181691 non-null  category
 33  nwoundte      181691 non-null  category
 34  property      181691 non-null  category
 35  propextent    181691 non-null  category
 36  ishostkid     181691 non-null  category
 37  ransom        181691 non-null  category
 38  INT_LOG       181691 non-null  category
 39  INT_IDEO      181691 non-null  category
 40  INT_MISC      181691 non-null  category
 41  INT_ANY       181691 non-null  category
dtypes: category(39), float64(2), int64(1)
memory usage: 11.7 MB

#### Set numeric variables to float

In [25]:
numeric = ['nperpcap', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte']
df[numeric] = df[numeric].astype(float)
eda_df[numeric] = eda_df[numeric].astype(float)

## Sort dataframe by year, month then day

In [26]:
sorted = df.sort_values(by=['iyear', 'imonth', 'iday'], axis=0, ascending=[True, True, True], 
                        inplace=False, kind='quicksort', na_position='first', ignore_index=True, key=None)
sorted_eda = eda_df.sort_values(by=['iyear', 'imonth', 'iday'], axis=0, ascending=[True, True, True], 
                        inplace=False, kind='quicksort', na_position='first', ignore_index=True, key=None)

In [27]:
sorted.head()

,latitude,longitude,eventid,iyear,imonth,iday,extended,country,region,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,targtype1,targsubtype1,natlty1,guncertain1,individual,nperpcap,claimed,weaptype1,weapsubtype1,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,ishostkid,ransom,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,19.371887,-99.086624,197000000002,1970,0,0,0,130,1,1.0,0.0,1,1,1,0.0,0.0,1,0,6,7,45.0,21.0,0.0,0,0.127628,0.0,13,16.0,0.000000,0.045981,0.508058,0.000000,0.038944,0.107163,0.0,3.0,1.0,1.0,0.0,1.0,1.0,1.0
1,15.478598,120.599741,197001000001,1970,1,0,0,160,5,4.0,0.0,1,1,1,0.0,0.0,1,0,1,10,54.0,217.0,0.0,0,0.127628,0.0,13,16.0,1.000000,0.045981,0.508058,0.000000,0.038944,0.107163,0.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
2,37.997490,23.762728,197001000002,1970,1,0,0,78,8,1.0,0.0,1,1,1,0.0,0.0,1,0,3,7,46.0,217.0,0.0,0,0.127628,0.0,6,16.0,2.403272,0.045981,0.508058,3.167668,0.038944,0.107163,1.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
3,33.580412,130.396361,197001000003,1970,1,0,0,101,4,1.0,0.0,1,1,1,0.0,0.0,1,0,7,7,46.0,217.0,0.0,0,0.127628,0.0,8,16.0,2.403272,0.045981,0.508058,3.167668,0.038944,0.107163,1.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
4,37.005105,-89.176269,197001010002,1970,1,1,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,2,3,22.0,217.0,0.0,0,0.127628,0.0,5,5.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
# remove rows that have invalid month and day
sorted = sorted[(sorted['imonth'] != 0) & (sorted['iday'] != 0)]
sorted_eda = sorted_eda[(sorted_eda['imonth'] != 0) & (sorted_eda['iday'] != 0)]
sorted.shape

(180800, 42)

In [29]:
sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 180800 entries, 4 to 181690
Data columns (total 42 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   latitude      180800 non-null  float64
 1   longitude     180800 non-null  float64
 2   eventid       180800 non-null  int64
 3   iyear         180800 non-null  category
 4   imonth        180800 non-null  category
 5   iday          180800 non-null  category
 6   extended      180800 non-null  category
 7   country       180800 non-null  category
 8   region        180800 non-null  category
 9   specificity   180800 non-null  category
 10  vicinity      180800 non-null  category
 11  crit1         180800 non-null  category
 12  crit2         180800 non-null  category
 13  crit3         180800 non-null  category
 14  doubtterr     180800 non-null  category
 15  multiple      180800 non-null  category
 16  success       180800 non-null  category
 17  suicide       180800 non-null  category
 18  attacktype1   180800 non-null  category
 19  targtype1     180800 non-null  category
 20  targsubtype1  180800 non-null  category
 21  natlty1       180800 non-null  category
 22  guncertain1   180800 non-null  category
 23  individual    180800 non-null  category
 24  nperpcap      180800 non-null  float64
 25  claimed       180800 non-null  category
 26  weaptype1     180800 non-null  category
 27  weapsubtype1  180800 non-null  category
 28  nkill         180800 non-null  float64
 29  nkillus       180800 non-null  float64
 30  nkillter      180800 non-null  float64
 31  nwound        180800 non-null  float64
 32  nwoundus      180800 non-null  float64
 33  nwoundte      180800 non-null  float64
 34  property      180800 non-null  category
 35  propextent    180800 non-null  category
 36  ishostkid     180800 non-null  category
 37  ransom        180800 non-null  category
 38  INT_LOG       180800 non-null  category
 39  INT_IDEO      180800 non-null  category
 40  INT_MISC      180800 non-null  category
 41  INT_ANY       180800 non-null  category
dtypes: category(32), float64(9), int64(1)
memory usage: 21.1 MB

In [30]:
sorted.head(20)

,latitude,longitude,eventid,iyear,imonth,iday,extended,country,region,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,targtype1,targsubtype1,natlty1,guncertain1,individual,nperpcap,claimed,weaptype1,weapsubtype1,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,ishostkid,ransom,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
4,37.005105,-89.176269,197001010002,1970,1,1,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,2,3,22.0,217.0,0.0,0,0.127628,0.0,5,5.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,43.468500,-89.744299,197001050001,1970,1,1,0,217,1,1.0,0.0,1,1,0,1.0,0.0,0,0,3,4,27.0,217.0,0.0,0,0.127628,0.0,6,16.0,0.000000,0.045981,0.508058,0.000000,0.038944,0.107163,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
6,-34.891151,-56.187214,197001020001,1970,1,2,0,218,3,1.0,0.0,1,1,1,0.0,0.0,0,0,1,3,25.0,218.0,0.0,0,0.127628,0.0,5,2.0,0.000000,0.045981,0.508058,0.000000,0.038944,0.107163,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
7,37.791927,-122.225906,197001020002,1970,1,2,0,217,1,1.0,0.0,1,1,1,1.0,0.0,1,0,3,21,107.0,217.0,0.0,0,0.127628,0.0,6,16.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
8,43.076592,-89.412488,197001020003,1970,1,2,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,7,4,28.0,217.0,0.0,0,1.000000,1.0,8,19.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
9,43.072950,-89.386694,197001030001,1970,1,3,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,7,2,21.0,217.0,0.0,0,1.000000,0.0,8,20.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
10,39.758968,-104.876305,197001060001,1970,1,6,0,217,1,1.0,0.0,1,1,1,1.0,0.0,1,0,7,4,28.0,217.0,0.0,0,0.127628,0.0,8,19.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,41.890961,12.490069,197001080001,1970,1,8,0,98,8,1.0,0.0,1,1,1,0.0,0.0,1,0,4,6,42.0,217.0,0.0,0,0.127628,0.0,5,4.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0
12,42.331685,-83.047924,197001090001,1970,1,9,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,7,2,21.0,217.0,0.0,0,0.127628,0.0,8,19.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
13,18.386932,-66.061127,197001090002,1970,1,9,0,217,1,1.0,0.0,1,1,1,1.0,0.0,1,0,7,1,7.0,217.0,1.0,0,0.127628,1.0,8,18.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
14,52.501530,13.401851,197001100001,1970,1,10,0,499,9,1.0,0.0,1,1,1,0.0,0.0,1,0,3,2,67.0,75.0,0.0,0,0.127628,0.0,6,16.0,2.403272,0.045981,0.508058,3.167668,0.038944,0.107163,0.0,3.0,0.0,0.0,0.0,1.0,1.0,1.0
15,23.498343,-458.695653,197001110001,1970,1,11,0,65,11,5.0,0.0,1,1,0,1.0,0.0,1,0,9,4,34.0,217.0,0.0,0,0.127628,0.0,13,16.0,1.000000,0.045981,0.508058,0.000000,0.038944,0.107163,0.0,3.0,0.0,0.0,0.0,1.0,1.0,1.0
16,40.697132,-73.931351,197001120001,1970,1,12,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,3,8,49.0,217.0,0.0,0,0.127628,0.0,6,31.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18.379998,-65.830948,197001120002,1970,1,12,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,3,1,4.0,217.0,0.0,0,0.127628,0.0,6,16.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
18,47.610786,-122.331306,197001130001,1970,1,13,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,7,1,7.0,217.0,0.0,0,0.127628,0.0,8,19.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
19,40.116748,-88.239270,197001140001,1970,1,14,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,7,3,22.0,217.0,0.0,0,0.127628,0.0,8,19.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
20,-34.891151,-56.187214,197001150001,1970,1,15,0,218,3,1.0,0.0,1,1,1,0.0,0.0,1,0,2,8,49.0,218.0,0.0,0,0.127628,0.0,5,2.0,0.000000,0.045981,0.508058,0.000000,0.038944,0.107163,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
21,47.610786,-122.331306,197001190002,1970,1,19,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,3,8,49.0,217.0,1.0,0,0.127628,0.0,6,16.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
22,47.610786,-122.331306,197001190003,1970,1,19,0,217,1,1.0,0.0,1,1,1,0.0,0.0,0,0,3,4,28.0,217.0,0.0,0,2.000000,0.0,6,16.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
23,40.717892,-74.067467,197001190004,1970,1,19,0,217,1,1.0,0.0,1,1,1,0.0,0.0,1,0,7,22,110.0,217.0,0.0,0,0.127628,0.0,8,18.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

## Create pickle file for cleaned data

In [31]:
sorted.to_pickle('data_ml.pickle')
sorted_eda.to_pickle('data_eda.pickle')